/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import databaseConnectivity.ConnectionClass;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hi
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productNameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantityTF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(725, 371));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADD PRODUCT...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 20, 160, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 100, 90, 30);
        getContentPane().add(productNameTF);
        productNameTF.setBounds(200, 100, 350, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Price:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 170, 70, 30);
        getContentPane().add(priceTF);
        priceTF.setBounds(200, 160, 350, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("P.Quantity:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 220, 80, 40);
        getContentPane().add(quantityTF);
        quantityTF.setBounds(200, 220, 350, 40);

        addButton.setText("Click here to add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(230, 280, 200, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    String name=productNameTF.getText();
    String price=priceTF.getText();
    String quantity=quantityTF.getText();
    if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PLEASE enter product name");
        } else if (price.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PLEASE Enter price");
        } else if(quantity.isEmpty())  {
            JOptionPane.showMessageDialog(null, " Enter product quantity "); 
        } else {
            final String searchStatement = "SELECT * from products where name=?";
            
            try {
                PreparedStatement searchPreparedStatement = ConnectionClass.getInstance().connection.prepareStatement(searchStatement);
                searchPreparedStatement.setString(1, name);
                
                ResultSet searhResultSet = searchPreparedStatement.executeQuery();
                
                while (searhResultSet.next()) {
                    JOptionPane.showMessageDialog(null, "product already exist");
                    return;
                }
                
                final String insertStatement = "INSERT INTO products(name, price, quantity) values(?,?,?)";
                PreparedStatement preparedStatementProduct = ConnectionClass.getInstance().connection.prepareStatement(insertStatement);
                preparedStatementProduct.setString(1, name);
                preparedStatementProduct.setString(2, price);
                preparedStatementProduct.setString(3, quantity);
               
                final int isAdded = preparedStatementProduct.executeUpdate();

                if (isAdded > 0) {
                    JOptionPane.showMessageDialog(null, "product added");
                    AdminDash adminDash=new AdminDash();
                    adminDash.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            } catch (SQLException ex) {
                System.out.println("error in " + AddProduct.class.getName() + " = " + ex);
            }
            
            
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField productNameTF;
    private javax.swing.JTextField quantityTF;
    // End of variables declaration//GEN-END:variables
}
