/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import databaseConnectivity.ConnectionClass;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.CatagoryModel;

/**
 *
 * @author hi
 */
public class AddProduct extends javax.swing.JFrame {
    
    ArrayList<CatagoryModel> categoriesModel = new ArrayList<CatagoryModel>();

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
        setCategories();
    }
    
    private void setCategories() {
        final String statement = "SELECT * from catagories";
        try {
            PreparedStatement preparedStatementCatagory = ConnectionClass.getInstance().connection.prepareStatement(statement);

            ResultSet resultSet = preparedStatementCatagory.executeQuery();
            categoriesComboBox.removeAllItems();
            while (resultSet.next()) {
                CatagoryModel cm = new CatagoryModel();
                
                cm.setID(resultSet.getInt("id"));
                cm.setName(resultSet.getString("catagoryname"));
                
                categoriesModel.add(cm);
                categoriesComboBox.addItem(cm.getName());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewCatagory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        productNameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        quantityTF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        categoriesComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(725, 371));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADD PRODUCT...");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 20, 160, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Name:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 140, 90, 30);
        getContentPane().add(productNameTF);
        productNameTF.setBounds(200, 130, 350, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Price:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 200, 70, 30);
        getContentPane().add(priceTF);
        priceTF.setBounds(200, 190, 350, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("P.Quantity:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 250, 80, 40);
        getContentPane().add(quantityTF);
        quantityTF.setBounds(200, 250, 350, 40);

        addButton.setText("Click here to add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(230, 310, 200, 30);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 20, 90, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("<--");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 20, 37, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Category");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 80, 90, 30);

        categoriesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(categoriesComboBox);
        categoriesComboBox.setBounds(200, 90, 72, 22);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    String name=productNameTF.getText();
    String price=priceTF.getText();
    String quantity=quantityTF.getText();
    String categoryName = categoriesComboBox.getSelectedItem().toString();
    
    if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PLEASE enter product name");
        } else if (price.isEmpty()) {
            JOptionPane.showMessageDialog(null, "PLEASE Enter price");
        } else if(quantity.isEmpty())  {
            JOptionPane.showMessageDialog(null, " Enter product quantity "); 
        } else if(categoryName.isEmpty()){
            JOptionPane.showMessageDialog(null, " select category ");  
        } 
        else {
            final String searchStatement = "SELECT * from products where name=?";
            
            try {
                PreparedStatement searchPreparedStatement = ConnectionClass.getInstance().connection.prepareStatement(searchStatement);
                searchPreparedStatement.setString(1, name);
                
                ResultSet searhResultSet = searchPreparedStatement.executeQuery();
                
                while (searhResultSet.next()) {
                    JOptionPane.showMessageDialog(null, "product already exist");
                    return;
                }
                
                final String insertStatement = "INSERT INTO products(name, price, quantity, category_id) values(?,?,?,?)";
                PreparedStatement preparedStatementProduct = ConnectionClass.getInstance().connection.prepareStatement(insertStatement);
                preparedStatementProduct.setString(1, name);
                preparedStatementProduct.setString(2, price);
                preparedStatementProduct.setString(3, quantity);
                
                for(CatagoryModel cm: categoriesModel) {
                    if (cm.getName().equals(categoryName)) {
                        preparedStatementProduct.setInt(4, cm.getID());
                        break;
                    }
                }
               
                final int isAdded = preparedStatementProduct.executeUpdate();

                if (isAdded > 0) {
                    JOptionPane.showMessageDialog(null, "product added");
                    
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            } catch (SQLException ex) {
                System.out.println("error in " + AddProduct.class.getName() + " = " + ex);
            }
            
            
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
AdminDash adminDash=new AdminDash();
                    adminDash.setVisible(true);
                    dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> categoriesComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField productNameTF;
    private javax.swing.JTextField quantityTF;
    // End of variables declaration//GEN-END:variables
}
