/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;
import databaseConnectivity.ConnectionClass;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.CatagoryModel;
import models.ProductModel;
/**
 *
 * @author hi
 */
public class UpdateProduct extends javax.swing.JFrame {
    ArrayList<CatagoryModel> categoriesModel = new ArrayList<CatagoryModel>();
    ProductModel productModel;
    /**
     * Creates new form UpdateProduct
     */
    public UpdateProduct() {
        initComponents();
        setCategories();
    }
    
    public UpdateProduct( ProductModel productModel) {
        initComponents();
        this.productModel = productModel;
        this.nameTF.setText(productModel.getName());
        this.priceTF.setText(productModel.getPrice());
        this.quantityTF.setText(productModel.getQuantity());
        setCategories();
    }
    
    private void setCategories() {
        final String statement = "SELECT * from catagories";
        try {
            PreparedStatement preparedStatementCatagory = ConnectionClass.getInstance().connection.prepareStatement(statement);
            ResultSet resultSet = preparedStatementCatagory.executeQuery();
            categoriesComboBox.removeAllItems();
            while (resultSet.next()) {
                CatagoryModel cm = new CatagoryModel();
                cm.setID(resultSet.getInt("id"));
                cm.setName(resultSet.getString("catagoryname"));
                categoriesModel.add(cm);
                categoriesComboBox.addItem(cm.getName());
            }
            
            for(CatagoryModel cm: categoriesModel) {
                if (cm.getID() == productModel.getCategoryID()) {
                    categoriesComboBox.setSelectedItem(cm.getName());
                    break;
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewCatagory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        priceTF = new javax.swing.JTextField();
        quantityTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        categoriesComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(612, 385));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("                            Update Product");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, 10, 420, 80);

        jLabel2.setText("Category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 90, 100, 30);

        jLabel3.setText("Price:-");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 200, 34, 16);

        jLabel4.setText("Quantity:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 250, 60, 20);
        getContentPane().add(nameTF);
        nameTF.setBounds(120, 130, 320, 30);
        getContentPane().add(priceTF);
        priceTF.setBounds(120, 190, 320, 30);
        getContentPane().add(quantityTF);
        quantityTF.setBounds(120, 250, 320, 30);

        jButton1.setText(" UPDATE  PRODUCT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 320, 150, 40);

        jButton2.setText("DELETE  PRODUCT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 320, 150, 40);

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 30, 72, 22);

        jLabel5.setText("Name:-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 130, 100, 30);

        categoriesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(categoriesComboBox);
        categoriesComboBox.setBounds(150, 100, 72, 22);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = nameTF.getText();
        String price = priceTF.getText();
        String quantity=quantityTF.getText();
        String categoryName = categoriesComboBox.getSelectedItem().toString();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter productname");
        } else if (price.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter product-price");
        }else if(quantity.isEmpty()) {
            JOptionPane.showMessageDialog(null,  "Enter product quantity");
        }else if(categoryName.isEmpty()) {
           JOptionPane.showMessageDialog(null,  "select category"); 
        } 
        
        else {
            final String searchStatement = "SELECT * from products where name=? && id!=?";

            try {
                PreparedStatement searchPreparedStatement = ConnectionClass.getInstance().connection.prepareStatement(searchStatement);
                searchPreparedStatement.setString(1, name);
                searchPreparedStatement.setString(2, Integer.toString(productModel.getID()));

                ResultSet searhResultSet = searchPreparedStatement.executeQuery();

                while (searhResultSet.next()) {
                    JOptionPane.showMessageDialog(null, "Product already exists");
                    return;
                }
                final String insertStatement = "update products set `name`=?, `price`=?, `quantity`=?, `category_id`=?  where `id`=?";
                PreparedStatement preparedStatementProduct = ConnectionClass.getInstance().connection.prepareStatement(insertStatement);
                preparedStatementProduct.setString(1, name);
                preparedStatementProduct.setString(2, price);
                preparedStatementProduct.setString(3, quantity);
               
                for(CatagoryModel cm: categoriesModel) {
                    if (cm.getName().equals(categoryName)) {
                        preparedStatementProduct.setInt(4, cm.getID());
                        break;
                    }
                }
                
                preparedStatementProduct.setString(5, Integer.toString(productModel.getID()));

                final int isAdded = preparedStatementProduct.executeUpdate();

                if (isAdded > 0) {
                    JOptionPane.showMessageDialog(null, "Value Updated");
                    ViewProduct viewProduct = new ViewProduct();
                viewProduct.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }
            } catch (SQLException ex) {
                System.out.println("error in " + AddProduct.class.getName() + " = " + ex);
            }
        }    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     final String statement = "delete from products where `id`=?";
        try {
            PreparedStatement preparedStatementProduct = ConnectionClass.getInstance().connection.prepareStatement(statement);
            preparedStatementProduct .setString(1, Integer.toString(productModel.getID()));
            int f=preparedStatementProduct .executeUpdate();
            if(f>0) {
                JOptionPane.showMessageDialog(null, "Product Deleted");
                ViewProduct viewProduct = new ViewProduct();
                viewProduct.setVisible(true);
                dispose();
            }
            else
            {
                System.out.println("Account Not Deleted");
                JOptionPane.showMessageDialog(null, "Account Not Deleted");
            }
        } catch (SQLException ex) {
                System.out.println("error in " + AddProduct.class.getName() + " = " + ex);
        }   //        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    ViewProduct obj=new ViewProduct();
    obj.setVisible(true);
    dispose();    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoriesComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField priceTF;
    private javax.swing.JTextField quantityTF;
    // End of variables declaration//GEN-END:variables
}
